# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Digital Fabrication Module
email: andrew.sleigh@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Work-in-progress and draft course notes for a module in digital fabrication at University of Brighton, based on Fab Academy
  
# Setup default URLs to be for github and github pages, so they will render correctly without overrides  
  
url: "https://andrewsleigh.github.io" # the base hostname & protocol for your site, e.g.   
baseurl: "/digital-fabrication-module" # the subpath of your site, e.g. /blog



# But also create some alternatives that can be substituted in when I build the site to deploy to my server

ascom_url: "https://andrewsleigh.com" # the base hostname & protocol for your site, e.g.   
ascom_baseurl: "/learning/digital-fabrication-module" # the subpath of your site, e.g. /blog


http://example.com
twitter_username: andrewsleigh
github_username:  andrewsleigh

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


permalink: /:categories/:title:output_ext
